### ISSUE TITLE
Generating load profile in linux, libraries required

### ISSUE THREAD

**Issue by brunorigal** [FZJ-IEK3-VSA/LoadProfileGenerator#10]
Hi, tanks for this nice software
I would like to run the software in linux. I did the chmod command you suggested in a closed issue. However, once it is done, how can I run the software? Does it need Wine?

**Comment by brunorigal** [comment]
Got it, it just needs [dotnet](https://docs.microsoft.com/fr-fr/dotnet/core/install/linux-ubuntu)

**Comment by brunorigal** [comment]
But now when I run: 
```
./simengine2 LaunchJsonParallel -d /home/user/household_config.json -ar /home/user/results/
```
I get the following error:
```
~/garbage/load_sim » ./simengine2 LaunchJsonParallel -d /home/user/garbage/load_generator_configs/res.json -ar /home/bruno/garbage/load_results                                           134 ↵ bruno@brg5
Command line:
LaunchJsonParallel
-d
/home/user/garbage/load_generator_configs/res.json
-ar
/home/bruno/garbage/load_results
Starting...
Initializing the logger
I Logfile path: (null), Logging to file: False, Severity: Debug, LogFileIndex: JsonParallelCalculationStarter
L Logfile path: (null), Logging to file: True, Severity: Debug, LogFileIndex: JsonParallelCalculationStarter
Starting (no thread name) #1: ParallelJsonLauncher.LaunchParallel
L Logfile path: (null), Logging to file: True, Severity: Debug, LogFileIndex: JsonParallelCalculationStarter
Reading options
Json Directory: /home/bruno/garbage/load_generator_configs/res.json
Maximum number of calculations to perform before quitting: -1
Number of cores to use: -1
Search in the subdirectories for files: False
Archiving folder is /home/user/garbage/load_results
Unhandled exception. Automation.ResultFiles.LPGException: simulationengine.exe was not found in the directory /home/bruno/garbage/load_sim
   at SimulationEngineLib.HouseJobProcessor.ParallelJsonLauncher.LaunchParallelInternal(ParallelJsonLauncherOptions options)
   at SimulationEngineLib.HouseJobProcessor.ParallelJsonLauncher.LaunchParallel(ParallelJsonLauncherOptions options)
   at SimulationEngineLib.CommandProcessor.LaunchJsonParallel(ParallelJsonLauncherOptions args)
--- End of stack trace from previous location ---
   at PowerArgs.ArgAction.Invoke()
   at PowerArgs.Args.<>c__DisplayClass17_1.<InvokeAction>b__3()
   at PowerArgs.Args.Execute[T](Func`1 argsProcessingCode)
   at PowerArgs.Args.<>c__DisplayClass17_0.<InvokeAction>b__2(String[] a)
   at PowerArgs.REPL.DriveREPL[T](TabCompletion t, Func`2 eval, String[] args, Func`1 defaultEval)
   at PowerArgs.Args.InvokeAction(CommandLineArgumentsDefinition definition, String[] args)
   at SimulationEngineLib.MainSimEngine.RunOptionProcessing(String connectionString, String[] args, String exename)
   at SimulationEngineLib.MainSimEngine.Run(String[] args, String exename)
   at SimEngine2.Program.Main(String[] args)
[1]    16961 abort (core dumped)  ./simengine2 LaunchJsonParallel -d 
```

**Comment by noah80** [comment]
The parallel running is not implemented in Linux, because for Linux there are very good tools to automate that already. This needs to be better documented though, so thanks for pointing that out.

Look for example at https://www.gnu.org/software/parallel/
This can be easily used together with the LPG.

**Comment by brunorigal** [comment]
Great it works well. Do you have some documentation concerning the simulation parameters files?

**Comment by noah80** [comment]
There is this: 
https://loadprofilegenerator.de/calculatinglargenumbers/

It's a bit outdated though.
